<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CrossQuest.CLI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrossQuest\CrossQuest.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="IPA.BuildProcess">
        <HintPath>..\Dependencies\IPA.BuildProcess.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.201">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Spectre.Console.Cli" Version="1.0.0-alpha.0.15" />
    </ItemGroup>

</Project>
